version: '3.8'

services:
   app:
      build:
         context: .
      ports:
         - '4000:4000'
      working_dir: /app
      #entrypoint: /app/entrypoint.sh
      command: "bash"
      volumes:
         - .:/app
   
